In [1]:
import polars as pl 
import numpy as np 
import cobra as cb
from pathlib import Path
from cobra.io.mat import load_matlab_model
from cobra.util import constraint_matrices, nullspace

In [3]:
moodel_path = Path("../../outputs/clus_vs_disp_redo/Disp.mat")

moodel = load_matlab_model(moodel_path)

No defined compartments in model model. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e, g, i, l, m, n, r, x

In [24]:
moodel_path.stem

'Disp'

In [4]:
moodel

In [16]:
moodel.reactions.get_by_id('biomass_maintenance').lower_bound = 25

In [17]:
moodel.reactions.get_by_id('biomass_maintenance')

In [23]:
growths = pl.read_csv("../../outputs/clus_vs_disp_redo/characterization/growths.csv")
{condition.name:condition[0] for condition in growths.iter_columns()}

{'Clus': 447.112640821751, 'Disp': 435.440291822407}

In [4]:
import sammi

In [25]:
subsystem = pl.read_csv("../../data/recon_reaction_names.csv")
subsystem

shape: (10_600, 2)
┌──────────────┬───────────────────────────┐
│ Reaction     ┆ subSystem                 │
│ ---          ┆ ---                       │
│ str          ┆ str                       │
╞══════════════╪═══════════════════════════╡
│ 10FTHF5GLUtl ┆ Transport, lysosomal      │
│ 10FTHF5GLUtm ┆ Transport, mitochondrial  │
│ 10FTHF6GLUtl ┆ Transport, lysosomal      │
│ 10FTHF6GLUtm ┆ Transport, mitochondrial  │
│ 10FTHF7GLUtl ┆ Transport, lysosomal      │
│ …            ┆ …                         │
│ CYOR_u10mi   ┆ Oxidative phosphorylation │
│ Htmi         ┆ Transport, mitochondrial  │
│ NADH2_u10mi  ┆ Oxidative phosphorylation │
│ CYOOm3i      ┆ Oxidative phosphorylation │
│ CYOOm2i      ┆ Oxidative phosphorylation │
└──────────────┴───────────────────────────┘

In [26]:
reactions = pl.read_csv("../../results/sampling_results/clus_vs_disp/differential reactions.csv")
reactions = reactions.join(subsystem, 'Reaction')
reactions.sort('fc', 'subSystem')

shape: (1_018, 4)
┌─────────────────┬─────────────┬──────┬──────────────────────────┐
│ Reaction        ┆ fc          ┆ pval ┆ subSystem                │
│ ---             ┆ ---         ┆ ---  ┆ ---                      │
│ str             ┆ f64         ┆ i64  ┆ str                      │
╞═════════════════╪═════════════╪══════╪══════════════════════════╡
│ EX_proglnpro[e] ┆ -469.180042 ┆ 0    ┆ Exchange/demand reaction │
│ TRPSERTYRr      ┆ -122.277109 ┆ 0    ┆ Peptide metabolism       │
│ TRPSERTYRt      ┆ -122.277109 ┆ 0    ┆ Transport, extracellular │
│ INSTt4          ┆ -98.501769  ┆ 0    ┆ Transport, extracellular │
│ EX_valtrpval[e] ┆ -79.181871  ┆ 0    ┆ Exchange/demand reaction │
│ …               ┆ …           ┆ …    ┆ …                        │
│ VALTRPVALt      ┆ 79.181871   ┆ 0    ┆ Transport, extracellular │
│ EX_trpsertyr[e] ┆ 122.277109  ┆ 0    ┆ Exchange/demand reaction │
│ EX_amp[e]       ┆ 178.972347  ┆ 0    ┆ Exchange/demand reaction │
│ PROGLNPROr      ┆ 469.180042  ┆ 0    ┆ Peptide metabolism       │
│ PROGLNPROt      ┆ 469.180042  ┆ 0    ┆ Transport, extracellular │
└─────────────────┴─────────────┴──────┴──────────────────────────┘

In [27]:
reactions.cast(pl.Utf8)

shape: (1_018, 4)
┌──────────────┬─────────────────────┬──────┬──────────────────────────┐
│ Reaction     ┆ fc                  ┆ pval ┆ subSystem                │
│ ---          ┆ ---                 ┆ ---  ┆ ---                      │
│ str          ┆ str                 ┆ str  ┆ str                      │
╞══════════════╪═════════════════════╪══════╪══════════════════════════╡
│ 10FTHFtm     ┆ 0.8945530180773418  ┆ 0    ┆ Transport, mitochondrial │
│ 34DHOXPEGOX  ┆ 0.8248386406955573  ┆ 0    ┆ Tyrosine metabolism      │
│ 34DHOXPEGt   ┆ 0.8248386406955573  ┆ 0    ┆ Transport, extracellular │
│ 34DHPHAMT    ┆ 0.9686315273615296  ┆ 0    ┆ Tyrosine metabolism      │
│ AATAi        ┆ -2.9422058280226975 ┆ 0    ┆ Lysine metabolism        │
│ …            ┆ …                   ┆ …    ┆ …                        │
│ 4HATVACIDthc ┆ -9.393254268532809  ┆ 0    ┆ Drug metabolism          │
│ ALLOP1tu     ┆ -0.9772530054436985 ┆ 0    ┆ Drug metabolism          │
│ CRVSM24tev   ┆ -5.2708440178118545 ┆ 0    ┆ Drug metabolism          │
│ IBUP_Rtdhep  ┆ 0.9748178126251867  ┆ 0    ┆ Drug metabolism          │
│ EX_M00260[e] ┆ -3.216370179200777  ┆ 0    ┆ Exchange/demand reaction │
└──────────────┴─────────────────────┴──────┴──────────────────────────┘

reactions.write_csv("../../results/sampling_results/clus_vs_disp/differential reactions subsystem.csv")

In [7]:
reactions.filter(pl.col("fc")>0).sort('fc',)

shape: (478, 4)
┌─────────────────┬────────────┬──────┬────────────────────────────┐
│ Reaction        ┆ fc         ┆ pval ┆ subSystem                  │
│ ---             ┆ ---        ┆ ---  ┆ ---                        │
│ str             ┆ f64        ┆ i64  ┆ str                        │
╞═════════════════╪════════════╪══════╪════════════════════════════╡
│ NDPK3n          ┆ 0.820024   ┆ 0    ┆ Nucleotide interconversion │
│ r2164           ┆ 0.822304   ┆ 0    ┆ Transport, extracellular   │
│ r1942           ┆ 0.822876   ┆ 0    ┆ Transport, extracellular   │
│ IDPtn           ┆ 0.824335   ┆ 0    ┆ Transport, nuclear         │
│ NDPK9n          ┆ 0.824335   ┆ 0    ┆ Nucleotide interconversion │
│ …               ┆ …          ┆ …    ┆ …                          │
│ VALTRPVALr      ┆ 79.181871  ┆ 0    ┆ Peptide metabolism         │
│ EX_trpsertyr[e] ┆ 122.277109 ┆ 0    ┆ Exchange/demand reaction   │
│ EX_amp[e]       ┆ 178.972347 ┆ 0    ┆ Exchange/demand reaction   │
│ PROGLNPROt      ┆ 469.180042 ┆ 0    ┆ Transport, extracellular   │
│ PROGLNPROr      ┆ 469.180042 ┆ 0    ┆ Peptide metabolism         │
└─────────────────┴────────────┴──────┴────────────────────────────┘

In [8]:
disp_rxn = reactions.filter(pl.col("fc")>0).sort('fc',descending=True)['Reaction'].to_list()

In [9]:
plot_data = (
    reactions
    .filter(pl.col('fc')>0) # Filter for condition 2
    .group_by('subSystem')
    .agg(pl.col('Reaction'), pl.col('fc'))
    .with_columns(subsystem_size = pl.col('Reaction').list.len())
    .sort('subsystem_size',descending=True)
)
plot_data[:10]

shape: (10, 4)
┌───────────────────────────┬──────────────────────────┬──────────────────────────┬────────────────┐
│ subSystem                 ┆ Reaction                 ┆ fc                       ┆ subsystem_size │
│ ---                       ┆ ---                      ┆ ---                      ┆ ---            │
│ str                       ┆ list[str]                ┆ list[f64]                ┆ u32            │
╞═══════════════════════════╪══════════════════════════╪══════════════════════════╪════════════════╡
│ Transport, extracellular  ┆ ["34DHOXPEGt",           ┆ [0.824839, 19.667735, …  ┆ 209            │
│                           ┆ "ALAGLNexR", … …         ┆ 0.9132…                  ┆                │
│ Exchange/demand reaction  ┆ ["EX_34dhoxpeg[e]",      ┆ [0.824839, 2.318831, …   ┆ 94             │
│                           ┆ "EX_4nph[e…              ┆ 0.92110…                 ┆                │
│ Peptide metabolism        ┆ ["ALALYSTHRr",           ┆ [1.345548, 1.015598, …   ┆ 70             │
│                           ┆ "ARGALATHRr", ……         ┆ 0.97397…                 ┆                │
│ Transport, mitochondrial  ┆ ["10FTHFtm", "CITRtm", … ┆ [0.894553, 5.015803, …   ┆ 22             │
│                           ┆ "HMR_…                   ┆ 20.4742…                 ┆                │
│ Nucleotide                ┆ ["CYTK10n", "CYTK11", …  ┆ [2.040652, 2.117552, …   ┆ 17             │
│ interconversion           ┆ "NDPK3…                  ┆ 2.11114…                 ┆                │
│ Fatty acid oxidation      ┆ ["C161CRN2t",            ┆ [9.208795, 2.198795, …   ┆ 11             │
│                           ┆ "C204CRNt", … "H…        ┆ 0.96476…                 ┆                │
│ Transport, endoplasmic    ┆ ["AHCYStr",              ┆ [0.825966, 0.993357, …   ┆ 8              │
│ reticul…                  ┆ "BILGLCURtr", … "H…      ┆ 1.62555…                 ┆                │
│ Miscellaneous             ┆ ["r0409", "r0587", …     ┆ [3.363584, 2.391333, …   ┆ 4              │
│                           ┆ "EX_gm1_h…               ┆ 3.05795…                 ┆                │
│ Cholesterol metabolism    ┆ ["LCAT25e", "LCAT43e", … ┆ [0.944243, 0.832966, …   ┆ 4              │
│                           ┆ "LCAT…                   ┆ 0.82599…                 ┆                │
│ Transport, nuclear        ┆ ["DTDPtn", "H2Otn", …    ┆ [2.517926, 0.969349, …   ┆ 4              │
│                           ┆ "HMR_109…                ┆ 1.04627…                 ┆                │
└───────────────────────────┴──────────────────────────┴──────────────────────────┴────────────────┘

In [10]:
plot_list = []
for  row in plot_data.iter_rows():
    plot_list.append(
        sammi.parser(row[0],row[1], row[2])
    )

In [11]:
sammi.plot(moodel, plot_list,opts=sammi.options("Disp.html"))

c:\Users\loksh\OneDrive - smail.iitm.ac.in\Projects\NUS collaboration\conda_env\Lib\site-packages\cobra\core\group.py:147: UserWarning: need to pass in a list
  warn("need to pass in a list")
c:\Users\loksh\OneDrive - smail.iitm.ac.in\Projects\NUS collaboration\conda_env\Lib\site-packages\cobra\core\metabolite.py:191: UserWarning: The element 'L' does not appear in the periodic table
  warn(f"The element {e} does not appear in the periodic table")
c:\Users\loksh\OneDrive - smail.iitm.ac.in\Projects\NUS collaboration\conda_env\Lib\site-packages\cobra\core\metabolite.py:191: UserWarning: The element 'X' does not appear in the periodic table
  warn(f"The element {e} does not appear in the periodic table")

In [12]:
len(disp_rxn)

478

In [13]:
model2 = cb.io.load_matlab_model("../../outputs/clus_vs_disp/Clus.mat")

No defined compartments in model model. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e, g, i, l, m, n, r, x

In [14]:
model2

In [15]:
plot_data_clus = (
    reactions
    .filter(pl.col('fc')<0) # Filter for condition 2
    .group_by('subSystem')
    .agg(pl.col('Reaction'), pl.col('fc'))
    .with_columns(subsystem_size = pl.col('Reaction').list.len())
    .sort('subsystem_size',descending=True)
)
plot_data_clus[:10]

shape: (10, 4)
┌───────────────────────────┬──────────────────────────┬──────────────────────────┬────────────────┐
│ subSystem                 ┆ Reaction                 ┆ fc                       ┆ subsystem_size │
│ ---                       ┆ ---                      ┆ ---                      ┆ ---            │
│ str                       ┆ list[str]                ┆ list[f64]                ┆ u32            │
╞═══════════════════════════╪══════════════════════════╪══════════════════════════╪════════════════╡
│ Transport, extracellular  ┆ ["ALADGLNexR",           ┆ [-2.15898, -1.770073, …  ┆ 254            │
│                           ┆ "BILDGLCURt", ……         ┆ -0.882…                  ┆                │
│ Exchange/demand reaction  ┆ ["EX_ach[e]",            ┆ [-6.637655, -3.485561, … ┆ 99             │
│                           ┆ "EX_gd1c_hs[e]",…        ┆ -3.21…                   ┆                │
│ Peptide metabolism        ┆ ["ARGALAPHEr",           ┆ [-3.446415, -6.209728, … ┆ 65             │
│                           ┆ "ARGCYSSERr", ……         ┆ -0.92…                   ┆                │
│ Transport, mitochondrial  ┆ ["ADNtm", "FUMtm", …     ┆ [-0.837546, -1.618242, … ┆ 20             │
│                           ┆ "HMR_2748…               ┆ -1.08…                   ┆                │
│ Nucleotide                ┆ ["ADK3m", "CYTK12", …    ┆ [-2.680437, -1.071177, … ┆ 18             │
│ interconversion           ┆ "NTD6"]                  ┆ -0.85…                   ┆                │
│ Fatty acid oxidation      ┆ ["C161CPT2", "C180CRNt", ┆ [-0.966403, -0.89699, …  ┆ 14             │
│                           ┆ … "HM…                   ┆ -5.338…                  ┆                │
│ Transport, endoplasmic    ┆ ["AMETr", "BILDGLCURtr", ┆ [-0.825966, -1.734846, … ┆ 9              │
│ reticul…                  ┆ … "HM…                   ┆ -1.28…                   ┆                │
│ Transport, peroxisomal    ┆ ["ARACHDCOAtx",          ┆ [-0.889019, -2.754146, … ┆ 5              │
│                           ┆ "TMNDNCCOAtx",…          ┆ -1.09…                   ┆                │
│ Miscellaneous             ┆ ["r0242", "RE0936E", …   ┆ [-3.403507, -4.716253, … ┆ 5              │
│                           ┆ "EX_5cy…                 ┆ -1.53…                   ┆                │
│ Purine catabolism         ┆ ["r0051", "RE2888C", …   ┆ [-3.430571, -0.860489, … ┆ 5              │
│                           ┆ "PUNP5"…                 ┆ -9.84…                   ┆                │
└───────────────────────────┴──────────────────────────┴──────────────────────────┴────────────────┘

In [16]:
plot_list_clus = []
for  row in plot_data_clus.iter_rows():
    plot_list_clus.append(
        sammi.parser(row[0],row[1], row[2])
    )

In [18]:
sammi.plot(model2, plot_list_clus, opts=sammi.options("Clus.html"))

In [19]:
plot_data

shape: (31, 4)
┌───────────────────────────┬──────────────────────────┬──────────────────────────┬────────────────┐
│ subSystem                 ┆ Reaction                 ┆ fc                       ┆ subsystem_size │
│ ---                       ┆ ---                      ┆ ---                      ┆ ---            │
│ str                       ┆ list[str]                ┆ list[f64]                ┆ u32            │
╞═══════════════════════════╪══════════════════════════╪══════════════════════════╪════════════════╡
│ Transport, extracellular  ┆ ["34DHOXPEGt",           ┆ [0.824839, 19.667735, …  ┆ 209            │
│                           ┆ "ALAGLNexR", … …         ┆ 0.9132…                  ┆                │
│ Exchange/demand reaction  ┆ ["EX_34dhoxpeg[e]",      ┆ [0.824839, 2.318831, …   ┆ 94             │
│                           ┆ "EX_4nph[e…              ┆ 0.92110…                 ┆                │
│ Peptide metabolism        ┆ ["ALALYSTHRr",           ┆ [1.345548, 1.015598, …   ┆ 70             │
│                           ┆ "ARGALATHRr", ……         ┆ 0.97397…                 ┆                │
│ Transport, mitochondrial  ┆ ["10FTHFtm", "CITRtm", … ┆ [0.894553, 5.015803, …   ┆ 22             │
│                           ┆ "HMR_…                   ┆ 20.4742…                 ┆                │
│ Nucleotide                ┆ ["CYTK10n", "CYTK11", …  ┆ [2.040652, 2.117552, …   ┆ 17             │
│ interconversion           ┆ "NDPK3…                  ┆ 2.11114…                 ┆                │
│ …                         ┆ …                        ┆ …                        ┆ …              │
│ Pyrimidine catabolism     ┆ ["D3AIBTm"]              ┆ [0.855777]               ┆ 1              │
│ Tryptophan metabolism     ┆ ["RE2349C"]              ┆ [1.813332]               ┆ 1              │
│ C5-branched dibasic acid  ┆ ["MECOAS1m"]             ┆ [0.859373]               ┆ 1              │
│ metab…                    ┆                          ┆                          ┆                │
│ Drug metabolism           ┆ ["IBUP_Rtdhep"]          ┆ [0.974818]               ┆ 1              │
│ Purine synthesis          ┆ ["AICART"]               ┆ [0.951765]               ┆ 1              │
└───────────────────────────┴──────────────────────────┴──────────────────────────┴────────────────┘

In [20]:
plot_data_clus

shape: (39, 4)
┌────────────────────────────┬───────────────────────┬────────────────────────────┬────────────────┐
│ subSystem                  ┆ Reaction              ┆ fc                         ┆ subsystem_size │
│ ---                        ┆ ---                   ┆ ---                        ┆ ---            │
│ str                        ┆ list[str]             ┆ list[f64]                  ┆ u32            │
╞════════════════════════════╪═══════════════════════╪════════════════════════════╪════════════════╡
│ Transport, extracellular   ┆ ["ALADGLNexR",        ┆ [-2.15898, -1.770073, …    ┆ 254            │
│                            ┆ "BILDGLCURt", ……      ┆ -0.882…                    ┆                │
│ Exchange/demand reaction   ┆ ["EX_ach[e]",         ┆ [-6.637655, -3.485561, …   ┆ 99             │
│                            ┆ "EX_gd1c_hs[e]",…     ┆ -3.21…                     ┆                │
│ Peptide metabolism         ┆ ["ARGALAPHEr",        ┆ [-3.446415, -6.209728, …   ┆ 65             │
│                            ┆ "ARGCYSSERr", ……      ┆ -0.92…                     ┆                │
│ Transport, mitochondrial   ┆ ["ADNtm", "FUMtm", …  ┆ [-0.837546, -1.618242, …   ┆ 20             │
│                            ┆ "HMR_2748…            ┆ -1.08…                     ┆                │
│ Nucleotide interconversion ┆ ["ADK3m", "CYTK12", … ┆ [-2.680437, -1.071177, …   ┆ 18             │
│                            ┆ "NTD6"]               ┆ -0.85…                     ┆                │
│ …                          ┆ …                     ┆ …                          ┆ …              │
│ Pentose phosphate pathway  ┆ ["HMR_4592"]          ┆ [-1.820602]                ┆ 1              │
│ Glycerophospholipid        ┆ ["r0480"]             ┆ [-0.837009]                ┆ 1              │
│ metabolism                 ┆                       ┆                            ┆                │
│ NAD metabolism             ┆ ["r0584"]             ┆ [-0.907573]                ┆ 1              │
│ Lysine metabolism          ┆ ["AATAi"]             ┆ [-2.942206]                ┆ 1              │
│ Pyrimidine synthesis       ┆ ["RE2954C"]           ┆ [-0.979202]                ┆ 1              │
└────────────────────────────┴───────────────────────┴────────────────────────────┴────────────────┘

In [23]:
flux = pl.read_parquet(
    "../../outputs/sampling/clus_vs_disp/common.parquet"
)
flux.sample(10)

shape: (10, 8_489)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 10FTHF7GL ┆ 10FTHF7GL ┆ 10FTHFtl  ┆ 10FTHFtm  ┆ … ┆ Htmi      ┆ NADH2_u10 ┆ CYOOm3i   ┆ experime │
│ Utl       ┆ Utm       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ mi        ┆ ---       ┆ nt       │
│ ---       ┆ ---       ┆ f32       ┆ f32       ┆   ┆ f32       ┆ ---       ┆ f32       ┆ ---      │
│ f32       ┆ f32       ┆           ┆           ┆   ┆           ┆ f32       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4.159247  ┆ 2.592376  ┆ -4.159247 ┆ 152.69899 ┆ … ┆ 547.89428 ┆ 49.426796 ┆ 449.83813 ┆ Disp     │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆ 5         ┆          │
│ 6.241165  ┆ 1.91161   ┆ -6.241165 ┆ 81.204636 ┆ … ┆ 564.98254 ┆ 83.989731 ┆ 484.95089 ┆ Disp     │
│           ┆           ┆           ┆           ┆   ┆ 4         ┆           ┆ 7         ┆          │
│ 2.723069  ┆ 0.060914  ┆ -2.723069 ┆ 84.693726 ┆ … ┆ 626.08459 ┆ 101.20307 ┆ 501.12429 ┆ Disp     │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 9         ┆ 8         ┆          │
│ 16.266958 ┆ 5.384442  ┆ -16.26695 ┆ 6.249233  ┆ … ┆ 633.16070 ┆ 101.15790 ┆ 585.48687 ┆ Clus     │
│           ┆           ┆ 8         ┆           ┆   ┆ 6         ┆ 6         ┆ 7         ┆          │
│ 9.825683  ┆ 2.345029  ┆ -9.825683 ┆ 2.682517  ┆ … ┆ 647.58184 ┆ 49.315735 ┆ 616.10888 ┆ Clus     │
│           ┆           ┆           ┆           ┆   ┆ 8         ┆           ┆ 7         ┆          │
│ 3.259458  ┆ 1.332554  ┆ -3.259458 ┆ 8.418118  ┆ … ┆ 563.20581 ┆ 72.139297 ┆ 563.52789 ┆ Clus     │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆           ┆ 3         ┆          │
│ 8.205741  ┆ 1.409781  ┆ -8.205741 ┆ 12.669044 ┆ … ┆ 623.14648 ┆ 79.850616 ┆ 569.36169 ┆ Clus     │
│           ┆           ┆           ┆           ┆   ┆ 4         ┆           ┆ 4         ┆          │
│ 5.067953  ┆ 4.677635  ┆ -5.067953 ┆ 104.99826 ┆ … ┆ 637.27404 ┆ 80.506248 ┆ 491.23330 ┆ Disp     │
│           ┆           ┆           ┆ 8         ┆   ┆ 8         ┆           ┆ 7         ┆          │
│ 3.19704   ┆ 0.420938  ┆ -3.19704  ┆ 0.66866   ┆ … ┆ 580.08721 ┆ 25.393251 ┆ 575.90289 ┆ Clus     │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆ 3         ┆          │
│ 7.960634  ┆ 5.136982  ┆ -7.960634 ┆ 8.218068  ┆ … ┆ 588.74456 ┆ 81.09304  ┆ 534.04199 ┆ Clus     │
│           ┆           ┆           ┆           ┆   ┆ 8         ┆           ┆ 2         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [42]:
flux.pivot(
    on = 'experiment',
    index = pl.selectors.exclude('experiment'),
    values= pl.selectors.exclude('experiment'),
    aggregate_function='mean'
)

shape: (20_000, 25_464)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 10FTHF7GL ┆ 10FTHF7GL ┆ 10FTHFtl  ┆ 10FTHFtm  ┆ … ┆ NADH2_u10 ┆ NADH2_u10 ┆ CYOOm3i_C ┆ CYOOm3i_ │
│ Utl       ┆ Utm       ┆ ---       ┆ ---       ┆   ┆ mi_Clus   ┆ mi_Disp   ┆ lus       ┆ Disp     │
│ ---       ┆ ---       ┆ f32       ┆ f32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f32       ┆ f32       ┆           ┆           ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 4.613117  ┆ 0.346264  ┆ -4.613117 ┆ 39.285633 ┆ … ┆ 16.287424 ┆ null      ┆ 689.85546 ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 9         ┆          │
│ 4.61374   ┆ 0.346987  ┆ -4.61374  ┆ 39.584473 ┆ … ┆ 16.081768 ┆ null      ┆ 688.79980 ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆          │
│ 4.614167  ┆ 0.347023  ┆ -4.614167 ┆ 39.584934 ┆ … ┆ 16.081238 ┆ null      ┆ 688.80011 ┆ null     │
│ 4.61253   ┆ 0.346467  ┆ -4.61253  ┆ 39.584015 ┆ … ┆ 16.083206 ┆ null      ┆ 688.80242 ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 9         ┆          │
│ 4.614835  ┆ 0.346826  ┆ -4.614835 ┆ 39.586399 ┆ … ┆ 16.141436 ┆ null      ┆ 688.88031 ┆ null     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 9.820356  ┆ 7.562842  ┆ -9.820356 ┆ 145.08522 ┆ … ┆ null      ┆ 91.979103 ┆ null      ┆ 473.4639 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 28       │
│ 9.661641  ┆ 7.636445  ┆ -9.661641 ┆ 139.02694 ┆ … ┆ null      ┆ 92.487778 ┆ null      ┆ 474.7896 │
│           ┆           ┆           ┆ 7         ┆   ┆           ┆           ┆           ┆ 42       │
│ 10.12718  ┆ 7.751074  ┆ -10.12718 ┆ 142.51901 ┆ … ┆ null      ┆ 92.445099 ┆ null      ┆ 475.2850 │
│           ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆ 95       │
│ 9.988547  ┆ 7.952035  ┆ -9.988547 ┆ 140.68589 ┆ … ┆ null      ┆ 91.965736 ┆ null      ┆ 474.8650 │
│           ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆ 21       │
│ 10.043198 ┆ 8.00452   ┆ -10.04319 ┆ 137.07344 ┆ … ┆ null      ┆ 92.144287 ┆ null      ┆ 474.7832 │
│           ┆           ┆ 8         ┆ 1         ┆   ┆           ┆           ┆           ┆ 95       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [46]:
flux.group_by('experiment').agg(pl.all().mean()).with_columns(pl.lit(1)).pivot(
    on = 'experiment',
    index = 'literal',
    values= pl.selectors.exclude('experiment'),
)

shape: (1, 16_979)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ literal ┆ 10FTHF7GLU ┆ 10FTHF7GL ┆ 10FTHF7GL ┆ … ┆ CYOOm3i_D ┆ CYOOm3i_C ┆ literal_D ┆ literal_C │
│ ---     ┆ tl_Disp    ┆ Utl_Clus  ┆ Utm_Disp  ┆   ┆ isp       ┆ lus       ┆ isp       ┆ lus       │
│ i32     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ f64        ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ i32       ┆ i32       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1       ┆ 7.462157   ┆ 9.62058   ┆ 4.703891  ┆ … ┆ 471.7992  ┆ 568.45725 ┆ 1         ┆ 1         │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [58]:
(
    flux
    .group_by('experiment')
    .agg(pl.all().mean())
    .pivot(
        on='experiment',
        index="dummy_index",
        values=pl.selectors.exclude('experiment'),
    )
)

shape: (1, 16_979)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ dummy_ind ┆ 10FTHF7GL ┆ 10FTHF7GL ┆ 10FTHF7GL ┆ … ┆ CYOOm3i_C ┆ CYOOm3i_D ┆ dummy_ind ┆ dummy_in │
│ ex        ┆ Utl_Clus  ┆ Utl_Disp  ┆ Utm_Clus  ┆   ┆ lus       ┆ isp       ┆ ex_Clus   ┆ dex_Disp │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1.0       ┆ 9.62058   ┆ 7.462157  ┆ 3.083415  ┆ … ┆ 568.45725 ┆ 471.7992  ┆ 1.0       ┆ 1.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [59]:
flux_pd = flux.to_pandas()

In [74]:
flux_pivoted = flux_pd.pivot_table(
    columns='experiment',
    aggfunc='mean',
)
flux_pivoted = pl.from_pandas(flux_pivoted, include_index=True).rename({'None':'Reaction'})
flux_pivoted

shape: (8_489, 3)
┌─────────────────────┬─────────────┬────────────┐
│ Reaction            ┆ Clus        ┆ Disp       │
│ ---                 ┆ ---         ┆ ---        │
│ str                 ┆ f64         ┆ f64        │
╞═════════════════════╪═════════════╪════════════╡
│ 10FTHF7GLUtl        ┆ 9.620584    ┆ 7.46216    │
│ 10FTHF7GLUtm        ┆ 3.083415    ┆ 4.703892   │
│ 10FTHFtl            ┆ -9.620584   ┆ -7.46216   │
│ 10FTHFtm            ┆ 7.125422    ┆ 128.021606 │
│ 11DOCRTSLte         ┆ 7.270179    ┆ 5.589819   │
│ …                   ┆ …           ┆ …          │
│ sink_tetdec2coa[c]  ┆ -25.029755  ┆ -8.793982  │
│ sink_tetdece1coa[c] ┆ -16.638071  ┆ -24.45936  │
│ sink_tmndnc[c]      ┆ 42.993748   ┆ -1.691928  │
│ sink_tmndnccoa[c]   ┆ -530.835388 ┆ -378.67804 │
│ sink_vitd3[c]       ┆ -10.480114  ┆ -10.935377 │
└─────────────────────┴─────────────┴────────────┘

In [75]:
subsystem

shape: (10_600, 2)
┌──────────────┬───────────────────────────┐
│ Reaction     ┆ subSystem                 │
│ ---          ┆ ---                       │
│ str          ┆ str                       │
╞══════════════╪═══════════════════════════╡
│ 10FTHF5GLUtl ┆ Transport, lysosomal      │
│ 10FTHF5GLUtm ┆ Transport, mitochondrial  │
│ 10FTHF6GLUtl ┆ Transport, lysosomal      │
│ 10FTHF6GLUtm ┆ Transport, mitochondrial  │
│ 10FTHF7GLUtl ┆ Transport, lysosomal      │
│ …            ┆ …                         │
│ CYOR_u10mi   ┆ Oxidative phosphorylation │
│ Htmi         ┆ Transport, mitochondrial  │
│ NADH2_u10mi  ┆ Oxidative phosphorylation │
│ CYOOm3i      ┆ Oxidative phosphorylation │
│ CYOOm2i      ┆ Oxidative phosphorylation │
└──────────────┴───────────────────────────┘

In [78]:
flux_pivoted.filter(pl.col('Reaction').is_in(reactions['Reaction'])).join(reactions, on='Reaction')

shape: (1_018, 6)
┌──────────────┬────────────┬────────────┬───────────┬──────┬──────────────────────────┐
│ Reaction     ┆ Clus       ┆ Disp       ┆ fc        ┆ pval ┆ subSystem                │
│ ---          ┆ ---        ┆ ---        ┆ ---       ┆ ---  ┆ ---                      │
│ str          ┆ f64        ┆ f64        ┆ f64       ┆ i64  ┆ str                      │
╞══════════════╪════════════╪════════════╪═══════════╪══════╪══════════════════════════╡
│ 10FTHFtm     ┆ 7.125422   ┆ 128.021606 ┆ 0.894553  ┆ 0    ┆ Transport, mitochondrial │
│ 34DHOXPEGOX  ┆ 48.990303  ┆ 510.383087 ┆ 0.824839  ┆ 0    ┆ Tyrosine metabolism      │
│ 34DHOXPEGt   ┆ 48.990303  ┆ 510.383087 ┆ 0.824839  ┆ 0    ┆ Transport, extracellular │
│ 34DHPHAMT    ┆ 4.596138   ┆ 288.44577  ┆ 0.968632  ┆ 0    ┆ Tyrosine metabolism      │
│ AATAi        ┆ 179.793015 ┆ -88.57859  ┆ -2.942206 ┆ 0    ┆ Lysine metabolism        │
│ …            ┆ …          ┆ …          ┆ …         ┆ …    ┆ …                        │
│ 4HATVACIDthc ┆ 3.956454   ┆ -4.899225  ┆ -9.393254 ┆ 0    ┆ Drug metabolism          │
│ ALLOP1tu     ┆ 196.925705 ┆ 2.265501   ┆ -0.977253 ┆ 0    ┆ Drug metabolism          │
│ CRVSM24tev   ┆ 1.661527   ┆ -2.439606  ┆ -5.270844 ┆ 0    ┆ Drug metabolism          │
│ IBUP_Rtdhep  ┆ 10.618748  ┆ 832.735107 ┆ 0.974818  ┆ 0    ┆ Drug metabolism          │
│ EX_M00260[e] ┆ 0.275914   ┆ -0.524892  ┆ -3.21637  ┆ 0    ┆ Exchange/demand reaction │
└──────────────┴────────────┴────────────┴───────────┴──────┴──────────────────────────┘

In [116]:
def construct_comprehensive_df(flux, reactions, subsystem, ):
    flux_pivoted = flux.to_pandas()
    flux_pivoted = flux_pivoted.pivot_table(
    columns='experiment',
    aggfunc='mean',
    )
    flux_pivoted = pl.from_pandas(flux_pivoted, include_index=True).rename({'None':'Reaction'})
    # flux_pivoted = pl.from_pandas(flux_pivoted, include_index=True)
    # print(flux_pivoted)
    # return flux_pivoted
    df = flux_pivoted.filter(pl.col('Reaction').is_in(reactions['Reaction'])).join(reactions, on='Reaction')
    df = df.join(subsystem, on='Reaction')
    return df

In [117]:
macir_dfs = Path("../../results/sampling_results/MACIR/").glob("*.csv")
macir_flux = pl.read_parquet("../../outputs/sampling/MACIR/common.parquet")

In [118]:
for file in macir_dfs:
    
    print(file.stem)
    
    macir_df = pl.read_csv(file)
    macir_df = construct_comprehensive_df(macir_flux, macir_df, subsystem)
    
    macir_df.write_csv(f"../../results/sampling_results/MACIR/{file.stem}_subsystem.csv")
    
    print("done")

s1c2_vs_s1k2
done
s1k1_vs_s1k1.fc5
done
s1k2_vs_s1k2.fc5
done
s1k_vs_s1k.fc5
done

In [ ]:
"../../results/sampling_results/MACIR"

shape: (596, 11)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ Reaction   ┆ S1C2       ┆ S1K        ┆ S1K1       ┆ … ┆ S1K_FC5   ┆ fc        ┆ pval ┆ subSystem │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---  ┆ ---       │
│ str        ┆ f32        ┆ f32        ┆ f32        ┆   ┆ f32       ┆ f64       ┆ i64  ┆ str       │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ 10FTHFtm   ┆ 25.666485  ┆ 304.292175 ┆ 64.600517  ┆ … ┆ 7.111106  ┆ -0.954329 ┆ 0    ┆ Transport │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ , mitocho │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ ndrial    │
│ 34DHOXPEGO ┆ 76.539467  ┆ -19.411505 ┆ 249.940048 ┆ … ┆ 156.87466 ┆ 1.282425  ┆ 0    ┆ Tyrosine  │
│ X          ┆            ┆            ┆            ┆   ┆ 4         ┆           ┆      ┆ metabolis │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ m         │
│ 34DHOXPEGt ┆ 76.539467  ┆ -19.411505 ┆ 249.940048 ┆ … ┆ 156.87466 ┆ 1.282425  ┆ 0    ┆ Transport │
│            ┆            ┆            ┆            ┆   ┆ 4         ┆           ┆      ┆ , extrace │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ llular    │
│ ACETONEt2  ┆ 8.782233   ┆ 7.565148   ┆ 8.959544   ┆ … ┆ -298.9319 ┆ -1.051929 ┆ 0    ┆ Transport │
│            ┆            ┆            ┆            ┆   ┆ 76        ┆           ┆      ┆ , extrace │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ llular    │
│ ACETONEt2m ┆ 8.782233   ┆ 7.565148   ┆ 8.959544   ┆ … ┆ -298.9319 ┆ -1.051929 ┆ 0    ┆ Transport │
│            ┆            ┆            ┆            ┆   ┆ 76        ┆           ┆      ┆ , mitocho │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ ndrial    │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …    ┆ …         │
│ ATVLACitr  ┆ -3.780172  ┆ 2.890864   ┆ -3.259059  ┆ … ┆ 0.164407  ┆ -0.892378 ┆ 0    ┆ Drug meta │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ bolism    │
│ EX_caproic ┆ 30.045494  ┆ -3.238559  ┆ -3.330709  ┆ … ┆ 13.338968 ┆ 1.641273  ┆ 0    ┆ Exchange/ │
│ [e]        ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ demand    │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ reaction  │
│ EX_M00260[ ┆ -0.559139  ┆ 0.622628   ┆ 0.322193   ┆ … ┆ -1.125161 ┆ -3.477961 ┆ 0    ┆ Exchange/ │
│ e]         ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ demand    │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ reaction  │
│ EX_M02745[ ┆ 4.912129   ┆ -0.61182   ┆ 4.848973   ┆ … ┆ 2.261453  ┆ 1.741765  ┆ 0    ┆ Exchange/ │
│ e]         ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ demand    │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ reaction  │
│ EX_M02837[ ┆ -24.027531 ┆ -542.53332 ┆ -20.012745 ┆ … ┆ -16.59692 ┆ 0.940633  ┆ 0    ┆ Exchange/ │
│ e]         ┆            ┆ 5          ┆            ┆   ┆ 2         ┆           ┆      ┆ demand    │
│            ┆            ┆            ┆            ┆   ┆           ┆           ┆      ┆ reaction  │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

# Ignore for now

In [15]:
m1 = load_matlab_model("../../outputs/TCGA-arid1a-avg/Truncating.mat")
m2 = load_matlab_model("../../outputs/TCGA-arid1a-avg/WT.mat")

m2

No defined compartments in model model. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e, g, i, l, m, n, r, x
No defined compartments in model model. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e, g, i, l, m, n, r, x

In [21]:
m1

In [16]:
for const in m1.constraints:
    print(const)
    
    break

10fthf5glu[c]: 0 <= 1.0*FPGS7 - 1.0*FPGS7_reverse_5df9f - 1.0*FPGS8 + 1.0*FPGS8_reverse_d2fc1 <= 0

In [17]:
res1 = constraint_matrices(m1)
res2 = constraint_matrices(m2)

In [22]:
res1.equalities

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  4., -4.]], shape=(4494, 14618))

In [23]:
res2.equalities

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  4., -4.]], shape=(4515, 14754))

In [24]:
print(np.linalg.cond(np.atleast_2d(res1.equalities)))
print(np.linalg.cond(np.atleast_2d(res2.equalities)))

5.6973396258840925e+31
6.293515347649145e+31

In [ ]:
np.linalg.matrix_rank(res1.equalities)

In [12]:
np.any([True, False])

np.True_

In [11]:
np.any(np.isnan(results.equalities))

np.False_

In [14]:
moodel.tolerance

1e-07

In [7]:
np.linalg.svd(results.equalities)

LinAlgError: SVD did not converge

In [8]:
from scipy.linalg import svd

In [9]:
svd(results.equalities)

LinAlgError: SVD did not converge

In [10]:
results.equalities.shape

(4526, 14792)

In [11]:
(np.abs(results.equalities) == np.inf).sum()

0

In [8]:
df = pl.read_csv("../../results/sampling_results/clus_vs_disp/clus_vs_disp_redo.csv", infer_schema_length=None)
df.filter(pl.col('Clus').is_null())

shape: (0, 6)
┌──────────┬─────┬──────┬──────┬──────┬───────────┐
│ Reaction ┆ fc  ┆ pval ┆ Clus ┆ Disp ┆ subSystem │
│ ---      ┆ --- ┆ ---  ┆ ---  ┆ ---  ┆ ---       │
│ str      ┆ f64 ┆ f64  ┆ str  ┆ str  ┆ str       │
╞══════════╪═════╪══════╪══════╪══════╪═══════════╡
└──────────┴─────┴──────┴──────┴──────┴───────────┘

In [13]:
df = df.with_columns(pl.col('Clus').cast(pl.Float32, strict=False), pl.col('Disp').cast(pl.Float32, strict=False))

In [18]:
df.filter((pl.col('Disp').is_null()) | (pl.col('fc') > 1))

shape: (478, 6)
┌───────────────┬──────────┬────────────┬─────────────┬───────────┬──────────────────────────┐
│ Reaction      ┆ fc       ┆ pval       ┆ Clus        ┆ Disp      ┆ subSystem                │
│ ---           ┆ ---      ┆ ---        ┆ ---         ┆ ---       ┆ ---                      │
│ str           ┆ f64      ┆ f64        ┆ f32         ┆ f32       ┆ str                      │
╞═══════════════╪══════════╪════════════╪═════════════╪═══════════╪══════════════════════════╡
│ 2DR1PP        ┆ -1.0     ┆ -12.32     ┆ 4.102718    ┆ null      ┆ Pyrimidine catabolism    │
│ 2HBO          ┆ 1.133483 ┆ 0.0        ┆ -175.056229 ┆ 10.952519 ┆ Propanoate metabolism    │
│ 2HBt2         ┆ 1.716522 ┆ 0.0        ┆ -251.18692  ┆ 66.254189 ┆ Transport, extracellular │
│ 3DPHBH2       ┆ -1.0     ┆ -12.364964 ┆ 0.437581    ┆ null      ┆ Ubiquinone synthesis     │
│ ACGALK        ┆ -1.0     ┆ -12.410256 ┆ 14.226833   ┆ null      ┆ Aminosugar metabolism    │
│ …             ┆ …        ┆ …          ┆ …           ┆ …         ┆ …                        │
│ EX_M02745[e]  ┆ 1.746905 ┆ 0.0        ┆ -1.417648   ┆ 5.213706  ┆ Exchange/demand reaction │
│ sink_asp_L[c] ┆ 1.0      ┆ -25.666667 ┆ -745.991577 ┆ null      ┆ Exchange/demand reaction │
│ sink_ser_L[c] ┆ 1.0      ┆ -25.862595 ┆ -741.114807 ┆ null      ┆ Exchange/demand reaction │
│ DM_4abut[c]   ┆ -1.0     ┆ -26.061538 ┆ 724.140137  ┆ null      ┆ Exchange/demand reaction │
│ DM_btn[n]     ┆ -1.0     ┆ -26.263566 ┆ 2.050219    ┆ null      ┆ Exchange/demand reaction │
└───────────────┴──────────┴────────────┴─────────────┴───────────┴──────────────────────────┘