In [3]:
import polars as pl 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pl.read_csv("../../data/dsp-data/GC_OB_DSP_All_AOIs_TMM_CPM.csv")
meta_df = pl.read_csv("../../data/dsp-data/GC_OB_DSP_All_AOIs_TMM_Metadata.csv")

In [5]:
df

shape: (18_676, 636)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ GeneID  ┆ T659_1_CD3 ┆ T659_1_CD ┆ T659_1_CK ┆ … ┆ N665_1_CK ┆ N665_2_CD ┆ N665_2_CK ┆ T665_1_CD │
│ ---     ┆ ---        ┆ 68        ┆ ---       ┆   ┆ ---       ┆ 3         ┆ ---       ┆ 3         │
│ str     ┆ f64        ┆ ---       ┆ f64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ ---       │
│         ┆            ┆ f64       ┆           ┆   ┆           ┆ f64       ┆           ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ DUSP12  ┆ 13.518994  ┆ 31.466331 ┆ 32.317849 ┆ … ┆ 43.162558 ┆ 38.191444 ┆ 26.567807 ┆ 28.517788 │
│ PGBD3   ┆ 40.556983  ┆ 23.599748 ┆ 26.102878 ┆ … ┆ 34.118974 ┆ 23.869653 ┆ 19.414936 ┆ 33.270753 │
│ RNF11   ┆ 13.518994  ┆ 47.199497 ┆ 31.074854 ┆ … ┆ 56.316861 ┆ 76.382888 ┆ 36.786195 ┆ 61.788541 │
│ MRPL11  ┆ 81.113965  ┆ 55.066079 ┆ 70.850668 ┆ … ┆ 55.905789 ┆ 57.287166 ┆ 40.87355  ┆ 33.270753 │
│ KY      ┆ 13.518994  ┆ 15.733166 ┆ 29.83186  ┆ … ┆ 30.419326 ┆ 42.965375 ┆ 28.611485 ┆ 52.282611 │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ PARD3   ┆ 27.037988  ┆ 62.932662 ┆ 38.532819 ┆ … ┆ 41.51827  ┆ 38.191444 ┆ 25.545968 ┆ 33.270753 │
│ CEP170B ┆ 67.594971  ┆ 15.733166 ┆ 21.130901 ┆ … ┆ 51.383997 ┆ 19.095722 ┆ 36.786195 ┆ 19.011859 │
│ DRAP1   ┆ 148.708936 ┆ 110.13215 ┆ 106.89749 ┆ … ┆ 66.59366  ┆ 133.67005 ┆ 48.026421 ┆ 76.047435 │
│         ┆            ┆ 9         ┆ 9         ┆   ┆           ┆ 5         ┆           ┆           │
│ PYGM    ┆ 13.518994  ┆ 39.332914 ┆ 21.130901 ┆ … ┆ 26.308607 ┆ 28.643583 ┆ 14.305742 ┆ 19.011859 │
│ DAB2    ┆ 54.075977  ┆ 141.59849 ┆ 38.532819 ┆ … ┆ 30.008254 ┆ 28.643583 ┆ 23.502291 ┆ 66.541505 │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
meta_df

shape: (652, 39)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SlideName ┆ ScanLabel ┆ ROILabel ┆ SegmentLa ┆ … ┆ ScanWidth ┆ ScanHeigh ┆ ScanOffse ┆ ScanOffse │
│ ---       ┆ ---       ┆ ---      ┆ bel       ┆   ┆ ---       ┆ t         ┆ tX        ┆ tY        │
│ str       ┆ str       ┆ i64      ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆ str       ┆   ┆           ┆ f64       ┆ i64       ┆ i64       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 20240305  ┆ 20230311  ┆ 10       ┆ CD3       ┆ … ┆ 35710.980 ┆ 77842.546 ┆ 6720      ┆ 2038      │
│ GC-OB     ┆ GC-OB     ┆          ┆           ┆   ┆ 47        ┆ 88        ┆           ┆           │
│ 02_03 DSP ┆ 02_03 DSP ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ WTA G…    ┆ WTA G…    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 20240305  ┆ 20230311  ┆ 10       ┆ CD68      ┆ … ┆ 35710.980 ┆ 77842.546 ┆ 6720      ┆ 2038      │
│ GC-OB     ┆ GC-OB     ┆          ┆           ┆   ┆ 47        ┆ 88        ┆           ┆           │
│ 02_03 DSP ┆ 02_03 DSP ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ WTA G…    ┆ WTA G…    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 20240305  ┆ 20230311  ┆ 10       ┆ CK        ┆ … ┆ 35710.980 ┆ 77842.546 ┆ 6720      ┆ 2038      │
│ GC-OB     ┆ GC-OB     ┆          ┆           ┆   ┆ 47        ┆ 88        ┆           ┆           │
│ 02_03 DSP ┆ 02_03 DSP ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ WTA G…    ┆ WTA G…    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 20240305  ┆ 20230311  ┆ 13       ┆ CD3       ┆ … ┆ 35710.980 ┆ 77842.546 ┆ 6720      ┆ 2038      │
│ GC-OB     ┆ GC-OB     ┆          ┆           ┆   ┆ 47        ┆ 88        ┆           ┆           │
│ 02_03 DSP ┆ 02_03 DSP ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ WTA G…    ┆ WTA G…    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 20240305  ┆ 20230311  ┆ 13       ┆ CD68      ┆ … ┆ 35710.980 ┆ 77842.546 ┆ 6720      ┆ 2038      │
│ GC-OB     ┆ GC-OB     ┆          ┆           ┆   ┆ 47        ┆ 88        ┆           ┆           │
│ 02_03 DSP ┆ 02_03 DSP ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ WTA G…    ┆ WTA G…    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 20240305  ┆ 20240311  ┆ 10       ┆ CD68      ┆ … ┆ 35679.640 ┆ 83331.367 ┆ 6736      ┆ 7486      │
│ GC-OB     ┆ GC-OB     ┆          ┆           ┆   ┆ 63        ┆ 19        ┆           ┆           │
│ 09_10 DSP ┆ 09_10 DSP ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ WTA G…    ┆ WTA G…    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 20240305  ┆ 20240311  ┆ 10       ┆ CK        ┆ … ┆ 35679.640 ┆ 83331.367 ┆ 6736      ┆ 7486      │
│ GC-OB     ┆ GC-OB     ┆          ┆           ┆   ┆ 63        ┆ 19        ┆           ┆           │
│ 09_10 DSP ┆ 09_10 DSP ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ WTA G…    ┆ WTA G…    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 20240305  ┆ 20240311  ┆ 11       ┆ CD3       ┆ … ┆ 35679.640 ┆ 83331.367 ┆ 6736      ┆ 7486      │
│ GC-OB     ┆ GC-OB     ┆          ┆           ┆   ┆ 63        ┆ 19        ┆           ┆           │
│ 09_10 DSP ┆ 09_10 DSP ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ WTA G…    ┆ WTA G…    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 20240305  ┆ 20240311  ┆ 11       ┆ CD68      ┆ … ┆ 35679.640 ┆ 83331.367 ┆ 6736      ┆ 7486      │
│ GC-OB     ┆ GC-OB     ┆          ┆           ┆   ┆ 63        ┆ 19        ┆           ┆           │
│ 09_10 DSP ┆ 09_10 DSP ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ WTA G…    ┆ WTA G…    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 20240305  ┆ 20240311  ┆ 11       ┆ CK        ┆ … ┆ 35679.640 ┆ 83331.367 ┆ 6736      ┆ 7486      │
│ GC-OB     ┆ GC-OB     ┆          ┆           ┆   ┆ 63        ┆ 19        ┆           ┆           │
│ 09_10 DSP ┆ 09_10 DSP ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ WTA G…    ┆ WTA G…    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
col_data = pl.DataFrame(schema=['colnames'], data=df.columns[1:])
col_data

shape: (635, 1)
┌─────────────┐
│ colnames    │
│ ---         │
│ str         │
╞═════════════╡
│ T659_1_CD3  │
│ T659_1_CD68 │
│ T659_1_CK   │
│ T659_2_CD3  │
│ T659_2_CD68 │
│ …           │
│ N665_1_CD3  │
│ N665_1_CK   │
│ N665_2_CD3  │
│ N665_2_CK   │
│ T665_1_CD3  │
└─────────────┘

In [8]:
col_data = (
    col_data
    .select(pl.col('colnames').str.split("_").list.to_struct())
    .unnest('colnames')    
)
col_data

shape: (635, 3)
┌─────────┬─────────┬─────────┐
│ field_0 ┆ field_1 ┆ field_2 │
│ ---     ┆ ---     ┆ ---     │
│ str     ┆ str     ┆ str     │
╞═════════╪═════════╪═════════╡
│ T659    ┆ 1       ┆ CD3     │
│ T659    ┆ 1       ┆ CD68    │
│ T659    ┆ 1       ┆ CK      │
│ T659    ┆ 2       ┆ CD3     │
│ T659    ┆ 2       ┆ CD68    │
│ …       ┆ …       ┆ …       │
│ N665    ┆ 1       ┆ CD3     │
│ N665    ┆ 1       ┆ CK      │
│ N665    ┆ 2       ┆ CD3     │
│ N665    ┆ 2       ┆ CK      │
│ T665    ┆ 1       ┆ CD3     │
└─────────┴─────────┴─────────┘

In [10]:
col_data['field_0'].value_counts().sort('count', descending=True)

shape: (126, 2)
┌─────────┬───────┐
│ field_0 ┆ count │
│ ---     ┆ ---   │
│ str     ┆ u32   │
╞═════════╪═══════╡
│ T643    ┆ 15    │
│ T237    ┆ 15    │
│ T644    ┆ 15    │
│ N645    ┆ 12    │
│ T239    ┆ 11    │
│ …       ┆ …     │
│ N403    ┆ 1     │
│ N659    ┆ 1     │
│ C12     ┆ 1     │
│ N431    ┆ 1     │
│ N424    ┆ 1     │
└─────────┴───────┘

In [11]:
col_data['field_2'].value_counts().sort('count',descending=True)

shape: (4, 2)
┌─────────┬───────┐
│ field_2 ┆ count │
│ ---     ┆ ---   │
│ str     ┆ u32   │
╞═════════╪═══════╡
│ CK      ┆ 181   │
│ CD3     ┆ 163   │
│ null    ┆ 146   │
│ CD68    ┆ 145   │
└─────────┴───────┘